import { config } from 'dotenv';

config();

const env = {
  PORT: process.env.PORT ?? 4000,

  FRONTEND_URL: process.env.FRONTEND_URL,

  SESSION_SECRET: process.env.SESSION_SECRET,

  //*JWT
  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_SECRET_KEY,
  JWT_TOKEN_EXPIRES_IN: process.env.JWT_TOKEN_EXPIRES_IN,
  JWT_REFRESH_TOKEN_EXPIRES_IN: process.env.JWT_REFRESH_TOKEN_EXPIRES_IN,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET_KEY,

  //*OAuth
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  NODEMAIL_MAIL: process.env.NODEMAIL_MAIL,
  NODEMAIL_MAIL_PASS: process.env.NODEMAIL_MAIL_PASS,

  //*CLOUDINARY
  CLOUD_NAME: process.env.CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_KEY_SECRET: process.env.CLOUDINARY_API_KEY_SECRET,

  //*STRIPE
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
};

export default env;
