import mongoose, { Document, ObjectId, Schema } from 'mongoose';

export enum NotificationType {
    SYSTEM = 'system',
    USER = 'user',
    ALERT = 'alert',
}

export enum NotificationStatus {
    PENDING = 'pending',
    SENT = 'sent',
    FAILED = 'failed',
    READ = 'read',
}

export interface ISender {
    model:String,
    id:ObjectId
}

export interface iRecipients {
    model:String,
    ids:ObjectId
}


export interface INotification extends Document {
    type: NotificationType;

    title: string;
    message: string;

    link?: string;
    attachmentUrl?: string;

    status: NotificationStatus;
    sent: boolean;
    autoGenerated: boolean;

    sender:ISender,
    recipients:iRecipients[],

    createdAt: Date;
    updatedAt: Date;
}


const NotificationsSchema = new Schema<INotification>(
    {
        type: {
            type: String,
            enum: Object.values(NotificationType),
            required: true,
        },

        title: { type: String,
            required: true,trim: true,},

        message: { type: String,
            required: true,trim: true,},

        link: {type: String},

        attachmentUrl: {type: String,},


        status: {
            type: String,
            enum: Object.values(NotificationStatus),
            default: NotificationStatus.PENDING,
        },

        sent: {
        type: Boolean,
        default: false,
        },

        autoGenerated: {
        type: Boolean,
        default: false,
        },

        sender: {
            model: {
                type: String,
                enum: ['Admin', 'Teacher'],
                required: true,
            },
            id: {
                type: Schema.Types.ObjectId,
                required: true,
                refPath: 'sender.model',
            },
        },


        recipients: [
        {
            model: {
                type: String,required: true,
                enum: ['Teacher', 'School', 'Center', 'Batch', 'Student'],
                },
            ids: [{
                type: Schema.Types.ObjectId,
                refPath: 'recipients.model',required: true,
            }],
        },
        ],

    },
    {
        timestamps: true,
        versionKey: false,
    }
);

export const notificationModel = mongoose.model<INotification>("Notifications",NotificationsSchema);



/**
 * Example
 * {
    "sender": {
        "model": "Admin",
        "id": "65fabc123..."
    },

    "recipients": [
        {
        "model": "Teacher",
        "ids": ["65aaa1...", "65aaa2..."]
        },
        {
        "model": "Center",
        "ids": ["65bbb1..."]
        }
    ]
    }

    sender=Admin
    reciever = center this should trigger all the peoples of that 
            particular school including the center;
            =Center - i need to find teacher, student.
            centerId
            document.teacherFind(centerId)



*/